import random


LEVEL_TESTS = {
    "A1": [
        {"topic": "to be", "question": "Choose the correct sentence.", "options": ["I am happy.", "I is happy.", "I be happy."], "answer": "I am happy."},
        {"topic": "articles", "question": "Choose the correct article: I have ___ apple.", "options": ["an", "a", "the"], "answer": "an"},
        {"topic": "plural nouns", "question": "Choose the correct plural form of 'book'.", "options": ["books", "bookes", "bookies"], "answer": "books"},
        {"topic": "present simple", "question": "Choose the correct sentence.", "options": ["She likes tea.", "She like tea.", "She liking tea."], "answer": "She likes tea."},
        {"topic": "possessive adjectives", "question": "Choose the correct word: This is ___ bag.", "options": ["my", "me", "I"], "answer": "my"},
        {"topic": "there is", "question": "Choose the correct sentence.", "options": ["There is a cat.", "There are a cat.", "There be a cat."], "answer": "There is a cat."},
        {"topic": "can", "question": "Choose the correct sentence.", "options": ["I can swim.", "I can to swim.", "I cans swim."], "answer": "I can swim."},
        {"topic": "questions with do", "question": "Choose the correct question.", "options": ["Do you like pizza?", "You do like pizza?", "Does you like pizza?"], "answer": "Do you like pizza?"},
        {"topic": "negative present simple", "question": "Choose the correct negative sentence.", "options": ["I don't know.", "I not know.", "I doesn't know."], "answer": "I don't know."},
        {"topic": "prepositions of place", "question": "Choose the correct word: The book is ___ the table.", "options": ["on", "at", "to"], "answer": "on"},
        {"topic": "have got", "question": "Choose the correct sentence.", "options": ["I have got a pen.", "I has got a pen.", "I got have a pen."], "answer": "I have got a pen."},
        {"topic": "demonstratives", "question": "Choose the correct word for one nearby object.", "options": ["this", "these", "those"], "answer": "this"},
        {"topic": "basic adjectives", "question": "Choose the opposite of 'big'.", "options": ["small", "old", "fast"], "answer": "small"},
        {"topic": "time", "question": "Choose the correct phrase.", "options": ["at five o'clock", "in five o'clock", "on five o'clock"], "answer": "at five o'clock"},
        {"topic": "countable nouns", "question": "Choose the correct sentence.", "options": ["There are two chairs.", "There is two chairs.", "There are two chair."], "answer": "There are two chairs."},
        {"topic": "object pronouns", "question": "Choose the correct word: I see ___ every day.", "options": ["him", "he", "his"], "answer": "him"},
        {"topic": "imperatives", "question": "Choose the correct instruction.", "options": ["Open the door.", "Opens the door.", "To open the door."], "answer": "Open the door."},
        {"topic": "like + noun", "question": "Choose the correct sentence.", "options": ["I like music.", "I like to music.", "I liking music."], "answer": "I like music."},
        {"topic": "short answers", "question": "Answer: Are you ready?", "options": ["Yes, I am.", "Yes, I do.", "Yes, I ready."], "answer": "Yes, I am."},
        {"topic": "days", "question": "Choose the correct preposition: ___ Monday.", "options": ["on", "in", "at"], "answer": "on"},
    ],
    "A2": [
        {"topic": "past simple regular", "question": "Choose the correct past form: I ___ TV yesterday.", "options": ["watched", "watch", "watching"], "answer": "watched"},
        {"topic": "past simple irregular", "question": "Choose the correct sentence.", "options": ["She went home.", "She goed home.", "She goes home yesterday."], "answer": "She went home."},
        {"topic": "comparatives", "question": "Choose the correct sentence.", "options": ["This book is cheaper.", "This book is more cheap.", "This book cheaper."], "answer": "This book is cheaper."},
        {"topic": "superlatives", "question": "Choose the correct form.", "options": ["the best", "the goodest", "the better"], "answer": "the best"},
        {"topic": "going to", "question": "Choose the correct sentence.", "options": ["I am going to study.", "I going to study.", "I am go to study."], "answer": "I am going to study."},
        {"topic": "present continuous", "question": "Choose the correct sentence.", "options": ["They are playing.", "They is playing.", "They play now."], "answer": "They are playing."},
        {"topic": "much/many", "question": "Choose the correct word: How ___ water do you need?", "options": ["much", "many", "a lot"], "answer": "much"},
        {"topic": "some/any", "question": "Choose the correct sentence.", "options": ["Do you have any questions?", "Do you have some questions?", "Do you have a questions?"], "answer": "Do you have any questions?"},
        {"topic": "must", "question": "Choose the correct sentence.", "options": ["You must wear a seatbelt.", "You must to wear a seatbelt.", "You must wearing a seatbelt."], "answer": "You must wear a seatbelt."},
        {"topic": "should", "question": "Choose the correct advice.", "options": ["You should rest.", "You should to rest.", "You should resting."], "answer": "You should rest."},
        {"topic": "will", "question": "Choose the correct future sentence.", "options": ["I will call you.", "I will to call you.", "I call will you."], "answer": "I will call you."},
        {"topic": "adverbs", "question": "Choose the correct sentence.", "options": ["He speaks slowly.", "He speaks slow.", "He slow speaks."], "answer": "He speaks slowly."},
        {"topic": "prepositions of movement", "question": "Choose the correct word: She walked ___ the room.", "options": ["into", "on", "at"], "answer": "into"},
        {"topic": "because", "question": "Choose the correct sentence.", "options": ["I stayed home because I was tired.", "I stayed home because of I was tired.", "I stayed home so I tired."], "answer": "I stayed home because I was tired."},
        {"topic": "too/enough", "question": "Choose the correct sentence.", "options": ["It is too cold.", "It is enough cold.", "It too is cold."], "answer": "It is too cold."},
        {"topic": "infinitive of purpose", "question": "Choose the correct sentence.", "options": ["I came here to learn.", "I came here for learn.", "I came here learning."], "answer": "I came here to learn."},
        {"topic": "past negative", "question": "Choose the correct sentence.", "options": ["I didn't see him.", "I didn't saw him.", "I not saw him."], "answer": "I didn't see him."},
        {"topic": "past questions", "question": "Choose the correct question.", "options": ["Did you enjoy it?", "Did you enjoyed it?", "Enjoyed you it?"], "answer": "Did you enjoy it?"},
        {"topic": "frequency adverbs", "question": "Choose the correct sentence.", "options": ["I usually drink coffee.", "I drink usually coffee.", "Usually I drink coffee always."], "answer": "I usually drink coffee."},
        {"topic": "requests", "question": "Choose the polite request.", "options": ["Could you help me?", "Do help me?", "Can to help me?"], "answer": "Could you help me?"},
    ],
    "B1": [
        {"topic": "present perfect", "question": "Choose the correct sentence.", "options": ["I have seen this film.", "I saw this film already.", "I have saw this film."], "answer": "I have seen this film."},
        {"topic": "present perfect vs past simple", "question": "Choose the best option: I ___ him yesterday.", "options": ["saw", "have seen", "seen"], "answer": "saw"},
        {"topic": "first conditional", "question": "Choose the correct sentence.", "options": ["If it rains, I will stay home.", "If it will rain, I stay home.", "If it rains, I stay home yesterday."], "answer": "If it rains, I will stay home."},
        {"topic": "second conditional", "question": "Choose the correct sentence.", "options": ["If I had time, I would travel.", "If I have time, I would travel.", "If I had time, I will travel."], "answer": "If I had time, I would travel."},
        {"topic": "passive voice", "question": "Choose the correct passive sentence.", "options": ["The letter was sent yesterday.", "The letter sent yesterday.", "The letter was send yesterday."], "answer": "The letter was sent yesterday."},
        {"topic": "reported speech", "question": "Choose the correct reported speech.", "options": ["He said he was tired.", "He said he is tired yesterday.", "He said he tired."], "answer": "He said he was tired."},
        {"topic": "gerund after enjoy", "question": "Choose the correct sentence.", "options": ["I enjoy reading.", "I enjoy to read.", "I enjoy read."], "answer": "I enjoy reading."},
        {"topic": "used to", "question": "Choose the correct sentence.", "options": ["I used to live here.", "I use to lived here.", "I used live here."], "answer": "I used to live here."},
        {"topic": "relative clauses", "question": "Choose the correct sentence.", "options": ["The man who called is my teacher.", "The man which called is my teacher.", "The man called who is my teacher."], "answer": "The man who called is my teacher."},
        {"topic": "modals of obligation", "question": "Choose the correct sentence.", "options": ["I have to finish this today.", "I must to finish this today.", "I have finish this today."], "answer": "I have to finish this today."},
        {"topic": "present perfect continuous", "question": "Choose the correct sentence.", "options": ["I have been waiting for an hour.", "I have waited since an hour.", "I am waiting since an hour."], "answer": "I have been waiting for an hour."},
        {"topic": "phrasal verbs", "question": "Choose the meaning of 'give up'.", "options": ["stop trying", "start quickly", "return something"], "answer": "stop trying"},
        {"topic": "so/such", "question": "Choose the correct sentence.", "options": ["It was such a good idea.", "It was so good idea.", "It was such good idea."], "answer": "It was such a good idea."},
        {"topic": "articles", "question": "Choose the correct sentence.", "options": ["The information was useful.", "An information was useful.", "Information were useful."], "answer": "The information was useful."},
        {"topic": "question tags", "question": "Choose the correct tag.", "options": ["You are coming, aren't you?", "You are coming, don't you?", "You are coming, are you?"], "answer": "You are coming, aren't you?"},
        {"topic": "past continuous", "question": "Choose the correct sentence.", "options": ["I was cooking when he called.", "I cooked when he was calling.", "I was cook when he called."], "answer": "I was cooking when he called."},
        {"topic": "although", "question": "Choose the correct sentence.", "options": ["Although it was late, we continued.", "Although it was late, but we continued.", "Despite it was late, we continued."], "answer": "Although it was late, we continued."},
        {"topic": "make/do", "question": "Choose the correct phrase.", "options": ["make a decision", "do a decision", "create a decision"], "answer": "make a decision"},
        {"topic": "wish", "question": "Choose the correct sentence.", "options": ["I wish I knew the answer.", "I wish I know the answer.", "I wish I would know the answer."], "answer": "I wish I knew the answer."},
        {"topic": "indirect questions", "question": "Choose the correct indirect question.", "options": ["Do you know where she lives?", "Do you know where does she live?", "Do you know where she live?"], "answer": "Do you know where she lives?"},
    ],
    "B2": [
        {"topic": "mixed conditionals", "question": "Choose the correct sentence.", "options": ["If I had studied, I would be confident now.", "If I studied, I would have been confident now.", "If I had studied, I will be confident now."], "answer": "If I had studied, I would be confident now."},
        {"topic": "third conditional", "question": "Choose the correct sentence.", "options": ["If she had left earlier, she would have arrived on time.", "If she left earlier, she would have arrived on time.", "If she had left earlier, she would arrive on time."], "answer": "If she had left earlier, she would have arrived on time."},
        {"topic": "advanced passive", "question": "Choose the correct sentence.", "options": ["The project is believed to be successful.", "The project believes to be successful.", "The project is believed being successful."], "answer": "The project is believed to be successful."},
        {"topic": "relative clauses", "question": "Choose the correct sentence.", "options": ["My brother, who lives abroad, is visiting us.", "My brother which lives abroad is visiting us.", "My brother, that lives abroad, is visiting us."], "answer": "My brother, who lives abroad, is visiting us."},
        {"topic": "inversion", "question": "Choose the correct sentence.", "options": ["Rarely have I seen such a view.", "Rarely I have seen such a view.", "Rarely have seen I such a view."], "answer": "Rarely have I seen such a view."},
        {"topic": "deduction", "question": "Choose the best option.", "options": ["He must have forgotten.", "He must forgot.", "He must has forgotten."], "answer": "He must have forgotten."},
        {"topic": "future perfect", "question": "Choose the correct sentence.", "options": ["By Friday, I will have finished it.", "By Friday, I will finish it already.", "By Friday, I will have finish it."], "answer": "By Friday, I will have finished it."},
        {"topic": "future continuous", "question": "Choose the correct sentence.", "options": ["This time tomorrow, I will be flying.", "This time tomorrow, I will flyed.", "This time tomorrow, I will flying."], "answer": "This time tomorrow, I will be flying."},
        {"topic": "verb patterns", "question": "Choose the correct sentence.", "options": ["I regret telling him.", "I regret to telling him.", "I regret tell him."], "answer": "I regret telling him."},
        {"topic": "participle clauses", "question": "Choose the correct sentence.", "options": ["Having finished the work, she left.", "Had finished the work, she left.", "Having finish the work, she left."], "answer": "Having finished the work, she left."},
        {"topic": "linking words", "question": "Choose the best connector.", "options": ["Nevertheless", "Because of", "Despite of"], "answer": "Nevertheless"},
        {"topic": "collocations", "question": "Choose the correct collocation.", "options": ["raise awareness", "lift awareness", "grow awareness"], "answer": "raise awareness"},
        {"topic": "subjunctive", "question": "Choose the correct sentence.", "options": ["It is important that he be informed.", "It is important that he is informed.", "It is important that he will be informed."], "answer": "It is important that he be informed."},
        {"topic": "cleft sentences", "question": "Choose the correct sentence.", "options": ["What I need is more time.", "That I need is more time.", "What I need it is more time."], "answer": "What I need is more time."},
        {"topic": "emphasis", "question": "Choose the correct sentence.", "options": ["Not only did she apologize, but she also helped.", "Not only she apologized, but she also helped.", "Not only did she apologized, but she also helped."], "answer": "Not only did she apologize, but she also helped."},
        {"topic": "articles with abstract nouns", "question": "Choose the correct sentence.", "options": ["Education is important.", "The education is important in general.", "An education is important in general."], "answer": "Education is important."},
        {"topic": "formal vocabulary", "question": "Choose the closest meaning of 'postpone'.", "options": ["delay", "cancel", "repeat"], "answer": "delay"},
        {"topic": "modals in the past", "question": "Choose the correct sentence.", "options": ["You should have called me.", "You should called me.", "You should have call me."], "answer": "You should have called me."},
        {"topic": "reported questions", "question": "Choose the correct sentence.", "options": ["She asked where I had been.", "She asked where had I been.", "She asked where I have been yesterday."], "answer": "She asked where I had been."},
        {"topic": "concession", "question": "Choose the correct sentence.", "options": ["Despite being tired, he continued.", "Despite he was tired, he continued.", "Despite of being tired, he continued."], "answer": "Despite being tired, he continued."},
    ],
    "C1": [
        {"topic": "nuanced modals", "question": "Choose the most natural sentence.", "options": ["He may well be right.", "He may good be right.", "He may be well right."], "answer": "He may well be right."},
        {"topic": "hedging", "question": "Choose the best academic phrase.", "options": ["This appears to suggest a pattern.", "This proves always a pattern.", "This surely says a pattern."], "answer": "This appears to suggest a pattern."},
        {"topic": "advanced inversion", "question": "Choose the correct sentence.", "options": ["Under no circumstances should you open it.", "Under no circumstances you should open it.", "Under no circumstances should open you it."], "answer": "Under no circumstances should you open it."},
        {"topic": "nominalisation", "question": "Choose the more formal option.", "options": ["The implementation of the plan was delayed.", "They delayed to implement the plan.", "The plan was delayed to implement."], "answer": "The implementation of the plan was delayed."},
        {"topic": "ellipsis", "question": "Choose the correct sentence.", "options": ["Some liked it; others didn't.", "Some liked it; others didn't liked.", "Some liked it; others not."], "answer": "Some liked it; others didn't."},
        {"topic": "discourse markers", "question": "Choose the best marker for contrast.", "options": ["Conversely", "Likewise", "Namely"], "answer": "Conversely"},
        {"topic": "advanced conditionals", "question": "Choose the correct sentence.", "options": ["Were it not for your help, I would fail.", "Was it not for your help, I would fail.", "Were it not your help, I would fail."], "answer": "Were it not for your help, I would fail."},
        {"topic": "reduced clauses", "question": "Choose the correct sentence.", "options": ["The people invited to the event arrived early.", "The people were invited to the event arrived early.", "The people inviting to the event arrived early."], "answer": "The people invited to the event arrived early."},
        {"topic": "subtle vocabulary", "question": "Choose the closest meaning of 'mitigate'.", "options": ["reduce the effect of", "make completely worse", "ignore carefully"], "answer": "reduce the effect of"},
        {"topic": "formal register", "question": "Choose the formal alternative to 'help'.", "options": ["assist", "make up", "sort out"], "answer": "assist"},
        {"topic": "preposition patterns", "question": "Choose the correct phrase.", "options": ["be consistent with", "be consistent to", "be consistent for"], "answer": "be consistent with"},
        {"topic": "emphatic structures", "question": "Choose the correct sentence.", "options": ["It was the timing that caused the issue.", "It was the timing what caused the issue.", "It was timing caused the issue."], "answer": "It was the timing that caused the issue."},
        {"topic": "advanced passive reporting", "question": "Choose the correct sentence.", "options": ["He is thought to have left.", "He is thought that left.", "He thought to have left."], "answer": "He is thought to have left."},
        {"topic": "concession clauses", "question": "Choose the correct sentence.", "options": ["Much as I agree, there are risks.", "Much as I am agree, there are risks.", "As much I agree, there are risks."], "answer": "Much as I agree, there are risks."},
        {"topic": "adverb position", "question": "Choose the natural sentence.", "options": ["She had barely arrived when it started raining.", "She barely had arrived when it started raining.", "Barely she had arrived when it started raining."], "answer": "She had barely arrived when it started raining."},
        {"topic": "collocation", "question": "Choose the correct collocation.", "options": ["draw a distinction", "paint a distinction", "make a distinguishing"], "answer": "draw a distinction"},
        {"topic": "register awareness", "question": "Choose the most neutral formal phrase.", "options": ["It is worth noting that...", "You gotta know that...", "It is super obvious that..."], "answer": "It is worth noting that..."},
        {"topic": "complex noun phrases", "question": "Choose the correct phrase.", "options": ["a rapidly growing demand for housing", "a demand rapidly growing for housing", "a rapid growing demand to housing"], "answer": "a rapidly growing demand for housing"},
        {"topic": "advanced linking", "question": "Choose the best phrase for adding a point.", "options": ["Furthermore", "Although", "Unless"], "answer": "Furthermore"},
        {"topic": "stance", "question": "Choose the cautious statement.", "options": ["The data may indicate a shift.", "The data definitely solves everything.", "The data cannot never change."], "answer": "The data may indicate a shift."},
    ],
    "C2": [
        {"topic": "idiomatic precision", "question": "Choose the most idiomatic sentence.", "options": ["The proposal leaves much to be desired.", "The proposal leaves many to desire.", "The proposal leaves desired much."], "answer": "The proposal leaves much to be desired."},
        {"topic": "subtle emphasis", "question": "Choose the correct sentence.", "options": ["What makes matters worse is the delay.", "What makes worse matters is the delay.", "What matter worse is the delay."], "answer": "What makes matters worse is the delay."},
        {"topic": "advanced register", "question": "Choose the most formal option.", "options": ["The findings are inconclusive.", "The findings are kind of unclear.", "The findings don't really say stuff."], "answer": "The findings are inconclusive."},
        {"topic": "rare inversion", "question": "Choose the correct sentence.", "options": ["Had I known, I would have acted differently.", "Had I knew, I would have acted differently.", "If had I known, I would have acted differently."], "answer": "Had I known, I would have acted differently."},
        {"topic": "nuanced vocabulary", "question": "Choose the closest meaning of 'ubiquitous'.", "options": ["found everywhere", "very rare", "recently invented"], "answer": "found everywhere"},
        {"topic": "concision", "question": "Choose the most concise formal sentence.", "options": ["The issue warrants further investigation.", "The issue is something that needs looking into more.", "The issue should maybe be checked more again."], "answer": "The issue warrants further investigation."},
        {"topic": "fixed expressions", "question": "Choose the correct phrase.", "options": ["for all intents and purposes", "for all intensive purposes", "for every intent purposes"], "answer": "for all intents and purposes"},
        {"topic": "advanced concession", "question": "Choose the correct sentence.", "options": ["Be that as it may, we must proceed.", "Be it as may that, we must proceed.", "As it may be that, we must proceed."], "answer": "Be that as it may, we must proceed."},
        {"topic": "semantic nuance", "question": "Choose the word closest to 'reluctant'.", "options": ["unwilling", "careless", "delighted"], "answer": "unwilling"},
        {"topic": "formal cohesion", "question": "Choose the best connector.", "options": ["Notwithstanding this limitation", "Because this limitation of", "Anyway limitation"], "answer": "Notwithstanding this limitation"},
        {"topic": "complex passive", "question": "Choose the correct sentence.", "options": ["The policy is expected to have been revised by June.", "The policy expects to have revised by June.", "The policy is expected having revised by June."], "answer": "The policy is expected to have been revised by June."},
        {"topic": "nominal style", "question": "Choose the most formal phrase.", "options": ["the subsequent deterioration of conditions", "conditions got worse after", "the later bad getting of conditions"], "answer": "the subsequent deterioration of conditions"},
        {"topic": "advanced collocation", "question": "Choose the correct collocation.", "options": ["pose a challenge", "put a challenge", "make a challenge to exist"], "answer": "pose a challenge"},
        {"topic": "pragmatics", "question": "Choose the most diplomatic sentence.", "options": ["That may need further refinement.", "That is completely wrong.", "You failed to do that."], "answer": "That may need further refinement."},
        {"topic": "cleft nuance", "question": "Choose the correct sentence.", "options": ["What concerns me is not the cost but the timing.", "What concerns me it is not the cost but the timing.", "What me concerns is not cost but timing."], "answer": "What concerns me is not the cost but the timing."},
        {"topic": "advanced prepositions", "question": "Choose the correct phrase.", "options": ["in keeping with tradition", "on keeping with tradition", "at keeping with tradition"], "answer": "in keeping with tradition"},
        {"topic": "legal/formal tone", "question": "Choose the formal equivalent of 'before'.", "options": ["prior to", "ahead on", "previous than"], "answer": "prior to"},
        {"topic": "subtle modal meaning", "question": "Choose the sentence meaning criticism about the past.", "options": ["You might have told me earlier.", "You might tell me earlier.", "You might have been tell me earlier."], "answer": "You might have told me earlier."},
        {"topic": "advanced discourse", "question": "Choose the best summarising phrase.", "options": ["Taken together, these points suggest caution.", "Taking together, these points suggest caution.", "Together taken, these points suggest caution."], "answer": "Taken together, these points suggest caution."},
        {"topic": "idiom", "question": "Choose the meaning of 'a double-edged sword'.", "options": ["something with both benefits and risks", "a perfect solution", "a useless tool"], "answer": "something with both benefits and risks"},
    ],
}


def get_level_test(level: str, count: int = 5) -> list[dict]:
    questions = random.sample(LEVEL_TESTS[level], count)
    result = []

    for question in questions:
        options = question["options"].copy()
        random.shuffle(options)
        result.append({
            "topic": question["topic"],
            "question": question["question"],
            "options": options,
            "correct_index": options.index(question["answer"]),
            "answer": question["answer"],
        })

    return result
