ROADMAP = {
    "A1": [
        "to be",
        "personal pronouns",
        "possessive adjectives",
        "articles",
        "this that these those",
        "plural nouns",
        "have got",
        "there is and there are",
        "present simple",
        "present simple negative",
        "present simple questions",
        "adverbs of frequency",
        "can and cannot",
        "imperatives",
        "basic question words",
        "object pronouns",
        "basic prepositions",
        "prepositions of place",
        "days and months",
        "time expressions",
        "countable and uncountable nouns",
        "some and any basics",
        "basic adjectives",
        "like love hate",
        "short answers",
    ],
    "A2": [
        "past simple",
        "past simple negative",
        "past simple questions",
        "past simple irregular verbs",
        "present continuous",
        "present continuous vs present simple",
        "comparatives",
        "superlatives",
        "going to",
        "will for predictions",
        "some and any",
        "much many a lot of",
        "how much and how many",
        "must and must not",
        "should and should not",
        "infinitive of purpose",
        "too and enough",
        "because and so",
        "requests and offers",
        "prepositions of movement",
        "basic future forms",
        "adverbs of manner",
        "present perfect introduction",
    ],
    "B1": [
        "present perfect",
        "present perfect vs past simple",
        "present perfect with for and since",
        "present perfect continuous",
        "first conditional",
        "second conditional",
        "zero conditional",
        "passive voice",
        "passive in different tenses",
        "reported speech",
        "reported questions",
        "gerunds and infinitives",
        "used to",
        "relative clauses",
        "defining relative clauses",
        "modals of obligation",
        "modals of advice",
        "past continuous",
        "past continuous vs past simple",
        "question tags",
        "indirect questions",
        "so and such",
        "articles with common nouns",
        "phrasal verbs basics",
        "wish and if only",
    ],
    "B2": [
        "future forms review",
        "third conditional",
        "mixed conditionals",
        "future perfect",
        "future continuous",
        "advanced passive",
        "passive reporting structures",
        "relative clauses",
        "non defining relative clauses",
        "modals in the past",
        "modals of deduction",
        "speculation and deduction",
        "inversion after negative adverbials",
        "participle clauses",
        "cleft sentences",
        "linking words for contrast",
        "linking words for result",
        "formal and informal style",
        "verb patterns",
        "advanced phrasal verbs",
        "collocations",
        "articles with abstract nouns",
        "reported statements and questions",
        "emphasis structures",
    ],
    "C1": [
        "advanced inversion",
        "hedging",
        "nominalisation",
        "formal register",
        "complex clauses",
        "advanced conditionals",
        "ellipsis and substitution",
        "reduced relative clauses",
        "advanced passive reporting",
        "discourse markers",
        "adverb position and emphasis",
        "concession clauses",
        "complex noun phrases",
        "stance and evaluation language",
        "advanced collocations",
        "preposition patterns",
        "subtle modal meanings",
        "academic style basics",
        "cohesion in longer answers",
        "register awareness",
    ],
    "C2": [
        "idiomatic precision",
        "subtle emphasis",
        "advanced discourse markers",
        "formal cohesion",
        "pragmatic nuance",
        "rare inversion patterns",
        "idiomatic collocations",
        "legal and formal tone",
        "semantic nuance",
        "advanced concession",
        "fixed expressions",
        "pragmatics and diplomacy",
        "cleft nuance",
        "high level concision",
        "nominal style",
        "advanced preposition choices",
        "rhetorical balance",
        "precision in argumentation",
        "natural high level paraphrasing",
        "native like register control",
    ],
}


def get_current_topic(user):
    topics = ROADMAP.get(user.level, [])
    index = user.current_topic_index or 0

    if index < 0:
        index = 0

    if index >= len(topics):
        return None

    return topics[index]


def update_progress(user, result):
    if result:
        user.current_topic_index = (user.current_topic_index or 0) + 1
        user.last_result = "correct"
        return

    if user.last_result in {"wrong", "wrong_twice"}:
        user.last_result = "wrong_twice"
    else:
        user.last_result = "wrong"
